# Generated by Django 2.2.11 on 2020-07-16 17:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField()),
                ('requester_email', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('notes', models.TextField()),
                ('start_timestamp', models.BigIntegerField()),
                ('end_timestamp', models.BigIntegerField()),
                ('remove_inactive_users_timeout', models.IntegerField()),
                ('creator_email', models.CharField(max_length=128)),
                ('config_json', models.TextField()),
                ('participant_count', models.IntegerField()),
            ],
            options={
                'unique_together': {('campaign_id', 'requester_email')},
            },
        ),
        migrations.CreateModel(
            name='GrpcUserIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256, unique=True)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('full_name', models.CharField(max_length=256)),
                ('day_no', models.IntegerField(default=None)),
                ('amount_of_data', models.IntegerField(default=None)),
                ('last_heartbeat_time', models.CharField(default=None, max_length=64)),
                ('last_sync_time', models.CharField(default=None, max_length=64)),
                ('data_source_ids', models.CharField(max_length=512, validators=[django.core.validators.int_list_validator])),
                ('per_data_source_amount_of_data', models.CharField(max_length=1024, validators=[django.core.validators.int_list_validator])),
                ('per_data_source_last_sync_time', models.CharField(max_length=2048)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET_Dashboard.Campaign')),
            ],
            options={
                'unique_together': {('email', 'campaign')},
            },
        ),
    ]
