# Generated by Django 2.2.11 on 2020-07-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.IntegerField(unique=True)),
                ('timestamp', models.BigIntegerField()),
                ('subject', models.CharField(max_length=512)),
                ('content', models.CharField(max_length=2048)),
            ],
        ),
    ]
