# Generated by Django 2.2.11 on 2020-07-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET_Dashboard', '0002_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
