# Generated by Django 2.2.11 on 2020-07-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET_Dashboard', '0003_notifications_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='campaign_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
