# Generated by Django 2.2.11 on 2020-09-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET_Dashboard', '0006_auto_20200909_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='grpc_id',
            field=models.IntegerField(),
        ),
    ]
